apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:12.2-alpine
          name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.be.ORG_DB_NAME }}
            - name: POSTGRES_USER
              value:  {{ .Values.be.ORG_DB_USERNAME }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.be.ORG_DB_PASSWORD }}

          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres-claim
      tolerations:
      - effect: NoSchedule
        key: userapp
        operator: Equal
        value: "true"      