apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudifytests.name" . }}-nginx-configmap
  labels:
    app: {{ template "cloudifytests.name" . }}-nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ tpl (.Files.Glob "files/cloudifytests-nginx.conf").AsConfig . | indent 2 }}
